Repository dmwm/WMCore, pull requests merged in 2018-06, with the labels that each got.

#8653 Added exit code 8033 - FileWriteError - to the list of exceptions
  src/python/WMCore/WMExceptions.py
Labels: Need crab branch, Need wmagent branch

#8652 split STAGEOUT_ERRORS for code 60317. Fix #8405
  src/python/WMCore/WMExceptions.py
Labels: Need crab branch

#8651 Reduce the BossAir memory footprint
  src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py
  src/python/WMCore/BossAir/BossAirAPI.py
  src/python/WMCore/BossAir/MySQL/LoadByWMBSID.py
  src/python/WMCore/WorkerThreads/BaseWorkerThread.py
  test/python/WMComponent_t/JobSubmitter_t/JobSubmitter_t.py
  test/python/WMCore_t/BossAir_t/BossAir_t.py
Labels: Need wmagent branch

#8650 Limit the number of archiveable jobs to be loaded each cycle
  etc/WMAgentConfig.py
  src/python/WMComponent/JobArchiver/JobArchiverPoller.py
  src/python/WMCore/WMBS/MySQL/Jobs/GetAllJobs.py
  src/python/WMCore/WMBS/Oracle/Jobs/GetAllJobs.py
Labels: Need wmagent branch

#8615 Strip the requirement string and proxy for Volunteer jobs
  src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py
Labels: Need wmagent branch

#8661 Limit number of jobs to cache in JobSubmitter; also order by task_id
  etc/WMAgentConfig.py
  src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py
  src/python/WMCore/WMBS/CreateWMBSBase.py
  src/python/WMCore/WMBS/MySQL/Jobs/ListForSubmitter.py
  src/python/WMCore/WMBS/Oracle/Create.py
  src/python/WMCore/WMBS/Oracle/Jobs/ListForSubmitter.py
  test/python/WMComponent_t/JobSubmitter_t/JobSubmitter_t.py
  test/python/WMCore_t/ResourceControl_t/ResourceControl_t.py
Labels: Need wmagent branch
