Repository dmwm/WMCore, pull requests merged in 2019-02, with the labels that each got.

#9002 Added PreMixingModule to MC mix modules - wmagent version
  src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py
Labels: Patch Production Agent

#9019 Do not parse scramOutput.log for debugging SCRAM problems
  src/python/WMCore/WMSpec/Steps/Diagnostics/CMSSW.py
  src/python/WMCore/WMSpec/Steps/ExecuteMaster.py
  src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
Labels: Do not merge yet, Work in progress

#8998 Record site status changes timestamp and allow grace period for drain…
  etc/WMAgentConfig.py
  src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py
  src/python/WMCore/ResourceControl/MySQL/ListThresholdsForSubmit.py
  src/python/WMCore/ResourceControl/ResourceControl.py
  src/python/WMCore/WMBS/CreateWMBSBase.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadFromID.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadFromIDWithType.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadFromIDWithWorkflow.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadFromName.py
  src/python/WMCore/WMBS/MySQL/Locations/New.py
  src/python/WMCore/WMBS/MySQL/Locations/SetState.py
  src/python/WMCore/WMBS/Oracle/Create.py
  src/python/WMCore/WMBS/Oracle/Locations/New.py
  test/python/WMComponent_t/JobSubmitter_t/JobSubmitter_t.py
  test/python/WMCore_t/WMBS_t/Locations_t.py
Labels: DB schema change

#9029 Added AgentStatusWatcher to the auto-restart components; send tail of…
  deploy/restartComponent.sh
Labels: Patch Production Agent

#9009 Use cmssw exit code from job report
  src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py
  test/python/WMCore_t/WMSpec_t/Steps_t/Executors_t/CMSSW_t.py
Labels: Need wmagent branch

#9030 Upper limit for MaxWallTimeSecs set to 45h
  etc/WMAgentConfig.py
Labels: Need wmagent branch, Patch Production Agent

#9050 Bundle of fixes for 1.1.20.patch5
  src/python/WMComponent/WorkQueueManager/WorkQueueManagerWMBSFileFeeder.py
  src/python/WMCore/Services/CRIC/CRIC.py
  src/python/WMCore/WMBS/Fileset.py
  src/python/WMCore/WMBS/Subscription.py
  src/python/WMCore/WMBS/Workflow.py
  src/python/WMCore/WorkQueue/WMBSHelper.py
  src/python/WMCore/WorkQueue/WorkQueue.py
Labels: Patch Production Agent
