Repository dmwm/WMCore, pull requests merged in 2019-07, with the labels that each got.

#9268 Getters/setters for CMSSW/WMStep object; fix StepChain straight to merge - wmagent version
  src/python/WMCore/WMSpec/StdSpecs/StdBase.py
  src/python/WMCore/WMSpec/StdSpecs/StepChain.py
  src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py
  src/python/WMCore/WMSpec/Steps/Templates/CMSSW.py
  src/python/WMCore/WMSpec/WMTask.py
  src/python/WMCore/WMSpec/WMWorkload.py
Labels: Patch Production Agent

#9279 Skip DBS3Upload cycle if it times out contacting wmstats
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
Labels: Need wmagent branch

#9283 Update deployment with the new PUT request behaviour for the agent config
  bin/wmagent-upload-config
  deploy/deploy-wmagent.sh
Labels: Do not merge yet

#9212 Add email alerting capability
  etc/WMAgentConfig.py
  src/python/Utils/EmailAlert.py
  src/python/WMComponent/AgentStatusWatcher/DrainStatusPoller.py
Labels: Need wmagent branch

#9292 Switch from WMCore StompAMQ to CMSMonitoring one
  requirements.txt
  setup_dependencies.py
  src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py
  src/python/WMCore/REST/HeartbeatMonitorBase.py
  src/python/WMCore/Services/StompAMQ/StompAMQ.py
Labels: Need wmagent branch

#9294 Fix LogCollect empty scramArch issue
  src/python/WMCore/WMSpec/Steps/Template.py
  src/python/WMCore/WMSpec/Steps/Templates/LogCollect.py
  src/python/WMCore/WMSpec/WMTask.py
Labels: Need wmagent branch
