Repository dmwm/WMCore, pull requests merged in 2019-05, with the labels that each got.

#9152 PY3: support urlparse in both py2 and py3 version
  bin/wmagent-couchapp-init
  bin/wmagent-mod-config
  src/python/WMCore/Lexicon.py
  src/python/WMCore/Services/Requests.py
  src/python/WMCore/Storage/TrivialFileCatalog.py
  src/python/WMCore/WMRuntime/SandboxCreator.py
  src/python/WMCore/WMRuntime/Scripts/UnpackUserTarball.py
  src/python/WMCore/WMSpec/Persistency.py
  src/python/WMCore/WorkQueue/DataLocationMapper.py
  src/python/WMQuality/WebTools/RESTClientAPI.py
Labels: Python3

#9174 Fix exception handling in DrainStatusPoller
  src/python/WMComponent/AgentStatusWatcher/DrainStatusPoller.py
Labels: Need wmagent branch

#9184 Add WMTool and SubmissionTool job classads
  src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py
Labels: Need wmagent branch

#9183 Minor improvements to WorkQueueManagerCleaner and more verbose
  src/python/WMComponent/TaskArchiver/TaskArchiverPoller.py
  src/python/WMComponent/WorkQueueManager/WorkQueueManagerCleaner.py
  src/python/WMCore/WorkQueue/WorkQueue.py
Labels: Need wmagent branch

#8935 WMAgent pypi packaging
  MANIFEST.in
  requirements.wmagent.txt
  requirements.wmcore.txt
  setup.py
  setup_wmagent.py
  setup_wmcore.py
  tools/build_pypi_packages.sh
Labels: Do not merge yet
