Repository dmwm/WMCore, pull requests merged in 2019-06, with the labels that each got.

#9237 Enable CherryPy stats for internal HTTP server
  src/python/WMCore/WebTools/Root.py
Labels: Do not merge yet

#9243 Set InnoDB tables to DYNAMIC row format; increased length of a few columns
  src/python/WMComponent/DBS3Buffer/MySQL/Create.py
  src/python/WMCore/Agent/Database/CreateAgentBase.py
  src/python/WMCore/Agent/Database/MySQL/Create.py
  src/python/WMCore/BossAir/MySQL/Create.py
  src/python/WMCore/ResourceControl/MySQL/Create.py
  src/python/WMCore/ResourceControl/Oracle/Create.py
  src/python/WMCore/ThreadPool/MySQL/Create.py
  src/python/WMCore/ThreadPool/MySQL/Queries.py
  src/python/WMCore/WMBS/CreateWMBSBase.py
  src/python/WMCore/WMBS/MySQL/Create.py
  src/python/WMCore/WMBS/MySQL/WorkUnit/Add.py
  src/python/WMCore/WMBS/Oracle/Create.py
  src/python/WMCore/WMBS/WorkUnit.py
  test/python/WMCore_t/WMBS_t/Fileset_t.py
Labels: Do not merge yet, Further tests needed, Need wmagent branch

#9235 Make APIMethodMismatch exception verbose to print details of what actually happened
  src/python/WMCore/REST/Error.py
  src/python/WMCore/REST/Server.py
Labels: Do not merge yet

#9255 Update PUT behaviour for ReqMgrAux APIs; use PUT method for updating CMSSW releases - wma branch
  bin/wmagent-upload-config
  src/python/WMComponent/AgentStatusWatcher/DrainStatusPoller.py
  src/python/WMCore/Cache/GenericDataCache.py
  src/python/WMCore/ReqMgr/CherryPyThreads/AuxCacheUpdateTasks.py
  src/python/WMCore/ReqMgr/Service/Auxiliary.py
  src/python/WMCore/Services/ReqMgr/ReqMgr.py
  src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py
Labels: Patch Production Agent

#9260 Handle oracle "not connected" as a soft error
  src/python/WMCore/Database/DBExceptionHandler.py
Labels: Do not merge yet, Need wmagent branch

#9265 Getters/setters for CMSSW/WMStep object; fix StepChain straight to merge
  src/python/WMCore/WMSpec/StdSpecs/StdBase.py
  src/python/WMCore/WMSpec/StdSpecs/StepChain.py
  src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py
  src/python/WMCore/WMSpec/Steps/Templates/CMSSW.py
  src/python/WMCore/WMSpec/WMTask.py
  src/python/WMCore/WMSpec/WMWorkload.py
  test/python/WMCore_t/WMSpec_t/Steps_t/Templates_t/CMSSWTemplate_t.py
  test/python/WMCore_t/WMSpec_t/WMWorkload_t.py
Labels: Need wmagent branch

#9264 Avoid WebTools depending on the REST package
  src/python/WMCore/WebTools/FrontEndAuth.py
  src/python/WMCore/WebTools/SecureDocumentation.py
Labels: need dbs branch

#9258 add doc string to generat proper docment.
  src/python/Utils/Throttled.py
Labels: need dbs branch

#9270 Set CMS_Type job classad based on the dashboard activity
  src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py
  src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py
  src/python/WMCore/BossAir/RunJob.py
  test/python/WMCore_t/BossAir_t/SimpleCondorPlugin_t.py
Labels: Need wmagent branch
