Repository dmwm/WMCore, pull requests merged in 2020-11, with the labels that each got.

#10011 [py2py3] WMCore/Algorithms - migration
  src/python/WMCore/Algorithms/MathAlgos.py
  src/python/WMCore/Algorithms/MiscAlgos.py
  src/python/WMCore/Algorithms/ParseXMLFile.py
  src/python/WMCore/Algorithms/Permissions.py
  src/python/WMCore/Algorithms/Singleton.py
  src/python/WMCore/Algorithms/SubprocessAlgos.py
Labels: Python3

#10067 Removing file status condition from GetUnsubscribedDatasets query
  src/python/WMComponent/RucioInjector/Database/MySQL/GetUnsubscribedDatasets.py
Labels: Do not merge yet

#9211 Code re-factoring and add timerange for user activities under throttling
  src/python/Utils/Throttled.py
  test/python/Utils_t/Throttled_t.py
Labels: Do not merge yet

#10012 [py2py3] Migrate WMCore/DataStructs
  src/python/WMCore/DataStructs/DASDocument.py
  src/python/WMCore/DataStructs/File.py
  src/python/WMCore/DataStructs/Fileset.py
  src/python/WMCore/DataStructs/Job.py
  src/python/WMCore/DataStructs/JobGroup.py
  src/python/WMCore/DataStructs/LumiList.py
  src/python/WMCore/DataStructs/Mask.py
  src/python/WMCore/DataStructs/MathStructs/ContinuousSummaryHistogram.py
  src/python/WMCore/DataStructs/MathStructs/SummaryHistogram.py
  src/python/WMCore/DataStructs/Run.py
  src/python/WMCore/DataStructs/Subscription.py
  src/python/WMCore/DataStructs/WorkUnit.py
  src/python/WMCore/DataStructs/Workflow.py
  test/python/WMCore_t/DataStructs_t/Fileset_t.py
  test/python/WMCore_t/DataStructs_t/JobPackage_t.py
  test/python/WMCore_t/DataStructs_t/Job_t.py
  test/python/WMCore_t/DataStructs_t/LumiList_t.py
  test/python/WMCore_t/DataStructs_t/MathStructs_t/ContinuousSummaryHistogram_t.py
  test/python/WMCore_t/DataStructs_t/MathStructs_t/DiscreteSummaryHistogram_t.py
  test/python/WMCore_t/DataStructs_t/Subscription_t.py
Labels: Python3

#10100 Split properly archived and force archived counters.
  src/python/WMCore/MicroService/DataStructs/DefaultStructs.py
  src/python/WMCore/MicroService/Unified/MSRuleCleaner.py
  test/python/WMCore_t/MicroService_t/Unified_t/MSRuleCleaner_t.py
Labels: Do not merge yet

#10112 Temporarily stop staging out log tarball to CASTOR
  src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
Labels: Patch Production Agent
