Repository dmwm/WMCore, pull requests merged in 2020-10, with the labels that each got.

#9985 Increase polling cycle for WorkQueueManagerLocationPoller to 1h - wmagent branch
  src/python/WMComponent/WorkQueueManager/WorkQueueManager.py
Labels: Patch Production Agent

#9983 Skip Tape (too) data placement for Resubmission workflows
  src/python/WMCore/MicroService/Unified/MSOutput.py
Labels: Patch Production Agent

#9971 [py2py3] Migrate WMCore/WMFactory
  src/python/WMCore/WMFactory.py
Labels: Python3

#9980 Disable PhEDExInjector; Enable all tiers to be injected in Rucio
  etc/WMAgentConfig.py
Labels: Need wmagent branch

#9978 Add getTransferInfo to MSOutput and info request to MSManager.
  src/python/WMCore/MicroService/Unified/MSManager.py
  src/python/WMCore/MicroService/Unified/MSOutput.py
Labels: Patch Production Agent

#9929 Decouple PhEDEx from the DBS3Reader wrapper module - crab branch
  src/python/WMCore/Services/DBS/DBS3Reader.py
  src/python/WMCore/Services/PhEDEx/PhEDEx.py
  src/python/WMCore/Services/PhEDEx/XMLDrop.py
  src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py
Labels: Do not merge yet

#10006 Deal with T0 output data subscription in RucioInjector
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
Labels: Need wmagent branch

#10029 a simple rucio.getPfn. Fix #9873
  src/python/WMCore/Services/Rucio/Rucio.py
  test/python/WMCore_t/Services_t/Rucio_t/Rucio_t.py
Labels: Rucio Transition

#10008 [py2py3] Migrate WMCore/Credential
  src/python/WMCore/Credential/Credential.py
  src/python/WMCore/Credential/Proxy.py
  src/python/WMCore/Credential/SimpleMyProxy.py
  test/python/WMCore_t/Credential_t/MyProxy_t.py
  test/python/WMCore_t/Credential_t/Proxy_t.py
Labels: Python3
