Repository dmwm/WMCore, pull requests merged in 2020-07, with the labels that each got.

#9781 Fix missing job report error codes
  src/python/WMComponent/JobAccountant/AccountantWorker.py
Labels: Need wmagent branch

#9740 [py2py3] futurize on WMCore/src/python/PSetTweaks
  src/python/PSetTweaks/PSetTweak.py
  src/python/PSetTweaks/WMTweak.py
Labels: Python3

#9731 [py2py3] futurize on WMCore/src/python/Utils
  src/python/Utils/CertTools.py
  src/python/Utils/EmailAlert.py
  src/python/Utils/ExtendedUnitTestCase.py
  src/python/Utils/IteratorTools.py
  src/python/Utils/MathUtils.py
  src/python/Utils/MemoryCache.py
  src/python/Utils/Pipeline.py
  src/python/Utils/ProcessStats.py
  src/python/Utils/Signals.py
  src/python/Utils/Throttled.py
  src/python/Utils/Timers.py
  src/python/Utils/Utilities.py
Labels: Python3

#9844 Force HEPCloud resources to be down in the CERN agents
  deploy/deploy-wmagent.sh
Labels: Need wmagent branch

#9839 [py2py3] Configuration - sys.version_info compatible with py2.6
  src/python/WMCore/Configuration.py
Labels: Need wmagent branch, Python3

#9693 Use PSN as PNN for opportunistic diskless resources
  src/python/WMCore/Services/CRIC/CRIC.py
  src/python/WMCore/WorkQueue/WorkQueue.py
  src/python/WMQuality/Emulators/CRICClient/MockCRICApi.py
Labels: Need wmagent branch

#9848 [py2py3] WMQuality.TestInit - Remove dependency on MySQL-python
  src/python/WMQuality/TestInit.py
Labels: Python3
