Repository dmwm/WMCore, pull requests merged in 2020-04, with the labels that each got.

#9603 Fix pop error when ssbStatus is unknown - wmagent branch
  src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py
Labels: Patch Production Agent

#9617 Created new component RucioInjector
  bin/wmagent-mod-config
  etc/WMAgentConfig.py
  src/python/Utils/MemoryCache.py
  src/python/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetDeletableBlocks.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetMigratedBlocks.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetUninjectedFiles.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetUnsubscribedDatasets.py
  src/python/WMComponent/RucioInjector/Database/MySQL/MarkBlocksDeleted.py
  src/python/WMComponent/RucioInjector/Database/MySQL/MarkDatasetSubscribed.py
  src/python/WMComponent/RucioInjector/Database/MySQL/__init__.py
  src/python/WMComponent/RucioInjector/Database/Oracle/GetDeletableBlocks.py
  src/python/WMComponent/RucioInjector/Database/Oracle/GetMigratedBlocks.py
  src/python/WMComponent/RucioInjector/Database/Oracle/GetUninjectedFiles.py
  src/python/WMComponent/RucioInjector/Database/Oracle/GetUnsubscribedDatasets.py
  src/python/WMComponent/RucioInjector/Database/Oracle/MarkBlocksDeleted.py
  src/python/WMComponent/RucioInjector/Database/Oracle/MarkDatasetSubscribed.py
  src/python/WMComponent/RucioInjector/Database/Oracle/__init__.py
  src/python/WMComponent/RucioInjector/Database/__init__.py
  src/python/WMComponent/RucioInjector/RucioInjector.py
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMComponent/RucioInjector/__init__.py
  src/python/WMCore/Services/Rucio/Rucio.py
  test/python/Utils_t/MemoryCache_t.py
  test/python/WMComponent_t/PhEDExInjector_t/PhEDExInjectorPoller_t.py
Labels: Need wmagent branch

#9627 Make list of allowed tiers for Rucio; disallowed tiers for PhEDEx
  etc/WMAgentConfig.py
  src/python/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  test/python/WMComponent_t/PhEDExInjector_t/PhEDExInjectorPoller_t.py
  test/python/WMComponent_t/PhEDExInjector_t/PhEDExInjectorSubscriber_t.py
  test/python/WMComponent_t/RucioInjector_t/RucioInjectorPoller_t.py
  test/python/WMComponent_t/RucioInjector_t/__init__.py
Labels: Need wmagent branch

#9626 Replace agentName WMAgentCommissioning by WMAgent
  bin/adhoc-scripts/drainAgent.py
  etc/GlobalWorkQueueConfig.py
  etc/WMAgentConfig.py
  src/couchapps/WMStats/_attachments/js/DataStruct/WMStats.GenericRequests.js
  src/couchapps/WMStats/_attachments/js/minified/import-all-t0.min.js
  src/couchapps/WMStats/_attachments/js/minified/import-all-t1.min.js
  src/python/WMCore/Services/WMStats/WMStatsReader.py
  src/python/WMQuality/Emulators/EmulatorSetup.py
  src/python/WMQuality/Emulators/WMSpecGenerator/ReqMgrDocGenerator.py
  test/data/WMStats/doc_generator.py
  test/data/WMStats/generator.py
  test/python/WMCore_t/Services_t/WMStats_t/WMStatsDocGenerator.py
Labels: Need wmagent branch

#9630 Added rule_id column to dbsbuffer_block; create a rule for every block produced
  etc/WMAgentConfig.py
  src/python/WMComponent/DBS3Buffer/MySQL/Create.py
  src/python/WMComponent/DBS3Buffer/Oracle/Create.py
  src/python/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetUnsubscribedBlocks.py
  src/python/WMComponent/RucioInjector/Database/MySQL/SetBlocksRule.py
  src/python/WMComponent/RucioInjector/Database/Oracle/GetUnsubscribedBlocks.py
  src/python/WMComponent/RucioInjector/Database/Oracle/SetBlocksRule.py
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMCore/Services/PhEDEx/DataStructs/SubscriptionList.py
  src/python/WMCore/Services/Rucio/Rucio.py
  test/python/WMComponent_t/PhEDExInjector_t/PhEDExInjectorSubscriber_t.py
Labels: DB schema change

#9618 Add runtime check for enforceGUIDInFileName
  src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py
  src/python/WMCore/WMRuntime/Tools/Scram.py
Labels: Need wmagent branch

#9649 Workaround voms-proxy-init imcompatibilities
  deploy/renew_proxy.sh
Labels: Need wmagent branch

#9648 RucioInjector has to close only those blocks injected into Rucio
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
Labels: Need wmagent branch

#9653 Bundle patch for WMAgent 1.3.3.patch1
  deploy/renew_proxy.sh
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py
  src/python/WMCore/WMRuntime/Tools/Scram.py
Labels: Patch Production Agent

#9662 Bundle patch for 1.3.3.patch2 agent
  src/python/WMCore/WMBS/MySQL/Locations/GetSiteInfo.py
  src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py
  src/python/WMCore/WorkQueue/WMBSHelper.py
  src/python/WMCore/WorkQueue/WorkQueue.py
Labels: Patch Production Agent

#9477 Update port and library for webtest in the REST unit tests
  test/python/WMCore_t/REST_t/Api_t.py
  test/python/WMCore_t/REST_t/Daemon_t.py
  test/python/WMCore_t/REST_t/Simple_t.py
Labels: Do not merge yet
