Repository dmwm/WMCore, pull requests merged in 2020-12, with the labels that each got.

#10105 Manage rule approval requirements for tape sites
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMCore/Services/Rucio/Rucio.py
  test/python/WMCore_t/Services_t/Rucio_t/Rucio_t.py
Labels: Need wmagent branch

#10122 add all Rucio lfns2pfns args. to getPFN. Fix #10056
  src/python/WMCore/Services/Rucio/Rucio.py
Labels: Need crab branch

#10130 Only resolve RSE requires_approval for T0 data placement
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
Labels: Need wmagent branch

#9997 Fix JobAccountant missing parent dbsbuffer file
  src/python/WMComponent/JobAccountant/AccountantWorker.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadForErrorHandler.py
  src/python/WMCore/WMBS/Oracle/Jobs/LoadForErrorHandler.py
  src/python/WMCore/WorkQueue/WMBSHelper.py
Labels: Need wmagent branch

#10152 Catch UnicodeDecodeError in JobAccountant
  src/python/WMComponent/JobAccountant/AccountantWorker.py
Labels: Need wmagent branch

#10103 [py2py3] Migration at level scr/python/A/B/C - slice 2
  src/python/WMCore/DAOFactory.py
  src/python/WMCore/Database/DBCreator.py
  src/python/WMCore/FwkJobReport/FileInfo.py
  src/python/WMCore/MicroService/Tools/PycurlRucio.py
  src/python/WMCore/ResourceControl/MySQL/ListThresholdsForCreate.py
  src/python/WMCore/ResourceControl/MySQL/ListThresholdsForSubmit.py
  src/python/WMCore/Services/Rucio/Rucio.py
  src/python/WMCore/Storage/TrivialFileCatalog.py
  src/python/WMCore/ThreadPool/ThreadSlave.py
  src/python/WMCore/WMBS/CreateWMBSBase.py
  src/python/WMCore/WMSpec/ConfigSectionTree.py
  src/python/WMCore/WebTools/FrontEndAuth.py
  src/python/WMCore/WebTools/Page.py
  src/python/WMQuality/Emulators/ReqMgrAux/MockReqMgrAux.py
  test/python/WMCore_t/GroupUser_t/Decorators_t.py
  test/python/WMCore_t/MicroService_t/Tools_t/PycurlRucio_t.py
  test/python/WMCore_t/Services_t/Rucio_t/Rucio_t.py
  test/python/WMCore_t/Storage_t/TrivialFileCatalog_t.py
  test/python/WMCore_t/WMSpec_t/ConfigSectionTree_t.py
Labels: Python3, py2py3 slice

#10174 [py2py3] Fix potential bug in WMException
  src/python/WMCore/WMException.py
  test/python/WMCore_t/WMException_t.py
Labels: Need wmagent branch, Python3

#10194 Fix pileup location with multi-RSE rules
  src/python/WMCore/Services/Rucio/Rucio.py
Labels: Need wmagent branch

#10205 MSTransferor: do not consider Rucio blocks with 0 or None size
  src/python/WMCore/MicroService/Unified/RequestInfo.py
Labels: Patch Production Services
