Repository dmwm/WMCore, pull requests merged in 2021-09, with the labels that each got.

#10783 Fix spec validation for Multicore/Memory/Streams/TpE - cmsweb branch
  src/python/WMCore/WMSpec/StdSpecs/Resubmission.py
  src/python/WMCore/WMSpec/StdSpecs/StepChain.py
  src/python/WMCore/WMSpec/StdSpecs/TaskChain.py
  src/python/WMCore/WMSpec/WMWorkloadTools.py
Labels: Patch Production Services

#10781 Fix spec validation for Multicore/Memory/Streams/TpE
  src/python/WMCore/ReqMgr/Utils/Validation.py
  src/python/WMCore/WMSpec/StdSpecs/Resubmission.py
  src/python/WMCore/WMSpec/StdSpecs/StepChain.py
  src/python/WMCore/WMSpec/StdSpecs/TaskChain.py
  src/python/WMCore/WMSpec/WMWorkloadTools.py
  test/python/WMCore_t/WMSpec_t/StdSpecs_t/Resubmission_t.py
  test/python/WMCore_t/WMSpec_t/StdSpecs_t/TaskChain_t.py
  test/python/WMCore_t/WMSpec_t/WMWorkloadTools_t.py
Labels: Need cmsweb branch

#10799 Add support and validation to GPU in StdBase/ReReco
  src/python/WMCore/Lexicon.py
  src/python/WMCore/WMSpec/StdSpecs/ReReco.py
  src/python/WMCore/WMSpec/StdSpecs/StdBase.py
  src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py
  src/python/WMCore/WMSpec/Steps/Templates/CMSSW.py
  src/python/WMCore/WMSpec/WMStep.py
  src/python/WMCore/WMSpec/WMTask.py
  src/python/WMCore/WMSpec/WMWorkload.py
  test/python/WMCore_t/Lexicon_t.py
  test/python/WMCore_t/WMSpec_t/Steps_t/Templates_t/CMSSWTemplate_t.py
  test/python/WMCore_t/WMSpec_t/WMStep_t.py
  test/python/WMCore_t/WMSpec_t/WMTask_t.py
  test/python/WMCore_t/WMSpec_t/WMWorkload_t.py
Labels: Update documentation

#10811 Propagate GPU requirements to job creation and submission
  src/python/WMComponent/JobCreator/JobCreatorPoller.py
  src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py
  src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py
  src/python/WMCore/BossAir/RunJob.py
  src/python/WMCore/WMSpec/WMTask.py
  test/python/WMCore_t/WMSpec_t/WMTask_t.py
Labels: squashing needed

#10817 Skip ErrorHandler cycle if agent configuration fails to be retrieved
  src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py
Labels: Need wmagent branch

#10757 Fix Unittests in Api_t.Tester
  src/python/WMCore/REST/Error.py
  src/python/WMCore/REST/Format.py
  src/python/WMCore/REST/Validation.py
  test/python/WMCore_t/REST_t/Api_t.py
Labels: Python3
