Repository dmwm/WMCore, pull requests merged in 2021-12, with the labels that each got.

#10905 Use siteLocalConfig in logCollect jobs to specify output site
  src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
Labels: Do not merge yet, Work in progress

#10902 Adding --deep option to getReplicaInfoForBlocks
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMCore/Services/Rucio/Rucio.py
  test/python/WMCore_t/Services_t/Rucio_t/Rucio_t.py
Labels: Do not merge yet, squashing needed

#10930 Remove trailing slash from DBS URL
  bin/adhoc-scripts/checkDsetFileCount.py
  bin/adhoc-scripts/workflowCompletion.py
  src/python/WMCore/MicroService/MSTransferor/Workflow.py
  src/python/WMCore/ReqMgr/DataStructs/Request.py
  src/python/WMCore/ReqMgr/Tools/cms.py
  src/python/WMCore/WMSpec/StdSpecs/StdBase.py
  src/python/WMCore/WMSpec/WMWorkload.py
  src/python/WMCore/WMSpec/WMWorkloadTools.py
  test/data/ReqMgr/requests/DMWM/DQMHarvest_RunWhitelist.json
  test/data/ReqMgr/requests/DMWM/ReReco_RunBlockWhite.json
  test/data/ReqMgr/requests/DMWM/ReReco_RunBlockWhite_Nvidia.json
  test/data/ReqMgr/requests/DMWM/ReReco_badBlocks.json
  test/data/ReqMgr/requests/DMWM/ReReco_failCase.json
  test/data/ReqMgr/requests/DMWM/ReReco_failCase_Nvidia.json
  test/data/ReqMgr/requests/DMWM/SC_6Steps_Scratch.json
  test/data/ReqMgr/requests/DMWM/StoreResults.json
  test/data/ReqMgr/requests/DMWM/TC_6Tasks_Scratch.json
  test/data/ReqMgr/requests/DMWM/TC_LHE_PFN.json
  test/data/ReqMgr/requests/DMWM/TC_PY3_ProdPsi.json
  test/data/ReqMgr/requests/DMWM/TaskChain_InclParents.json
  test/data/ReqMgr/requests/DMWM/TaskChain_ProdMinBias.json
  test/data/ReqMgr/requests/DMWM/TaskChain_ProdMinBias_Nvidia.json
  test/data/ReqMgr/requests/Integration/DQMHarvesting.json
  test/data/ReqMgr/requests/Integration/DQMHarvesting_LumiMask.json
  test/data/ReqMgr/requests/Integration/DQMHarvesting_MultiRun.json
  test/data/ReqMgr/requests/Integration/ReReco_LumiMask.json
  test/data/ReqMgr/requests/Integration/ReReco_Parents.json
  test/data/ReqMgr/requests/Integration/SC_LHE_Ext.json
  test/data/ReqMgr/requests/Integration/SC_LumiMask_Rules.json
  test/data/ReqMgr/requests/Integration/SC_MultiPU.json
  test/data/ReqMgr/requests/Integration/SC_PY3_PURecyc.json
  test/data/ReqMgr/requests/Integration/SC_ReDigi_Harvest_Prod.json
  test/data/ReqMgr/requests/Integration/SC_Straight.json
  test/data/ReqMgr/requests/Integration/StepChain_InclParents.json
  test/data/ReqMgr/requests/Integration/TC_Drop_PhEDEx_Ext.json
  test/data/ReqMgr/requests/Integration/TC_PY3_Data_LumiList.json
  test/data/ReqMgr/requests/Integration/TC_PY3_TTbarPU.json
  test/data/ReqMgr/requests/Integration/TaskChain_LumiMask_multiRun.json
  test/data/ReqMgr/requests/Integration/TaskChain_MC.json
  test/data/ReqMgr/requests/Integration/TaskChain_PUMCRecyc.json
  test/data/ReqMgr/requests/Integration/TaskChain_Prod.json
  test/data/ReqMgr/requests/Static/BatchRequestsDump.json
  test/data/ReqMgr/requests/Static/IncludeParentsRequestDump.json
  test/data/ReqMgr/requests/Static/MultiPURequestDump.json
  test/data/ReqMgr/requests/Static/RelVal_Premix.json
  test/data/ReqMgr/requests/Static/StepChainRequestDump.json
  test/data/ReqMgr/requests/Static/StepChain_MCStatic.json
  test/data/ReqMgr/requests/Static/StepChain_multiPU.json
  test/data/ReqMgr/requests/Static/TaskChainRequestDump.json
  test/data/ReqMgr/requests/Static/TaskChain_MCRecyc.json
  test/data/ReqMgr/requests/Static/TaskChain_multiPU.json
  test/data/ReqMgr/requests/Static/singleRequestDump.json
  test/python/WMCore_t/MicroService_t/MSTransferor_t/Workflow_t.py
  test/python/WMCore_t/WMSpec_t/StdSpecs_t/DQMHarvest_t.py
  test/python/WMCore_t/WMStats_t/DataStructs_t/DataCache.json
  test/python/WMCore_t/WorkQueue_t/DataStructs_t/wq_available_elements.json
Labels: Do not merge yet

#10923 Add getStatsFromMongoDB to MSUnmerged.
  src/python/WMCore/MicroService/MSManager.py
  src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
  src/python/WMCore/MicroService/Service/Data.py
Labels: squashing needed, Update documentation

#10932 Stop using password for MariaDB localhost users
  deploy/WMAgent.production
  deploy/WMAgent.testbed
  deploy/deploy-wmagent.sh
  test/deploy/WMAgent_unittest.secrets
  test/deploy/deploy_unittest.sh
  test/deploy/deploy_unittest_py3.sh
  test/deploy/env_unittest.sh
  test/deploy/env_unittest_py3.sh
Labels: Further tests needed
