Repository dmwm/WMCore, pull requests merged in 2021-02, with the labels that each got.

#10252 Trap SSL_connect error and Service Unavailable in DBSUploadPoller
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
  test/python/WMComponent_t/DBS3Buffer_t/DBSUpload_t.py
Labels: Need wmagent branch

#10250 [py2py3] pycurl_manager - better handling of curl.setopts() input arguments
  src/python/Utils/Utilities.py
  src/python/WMCore/Services/pycurl_manager.py
  test/python/WMCore_t/Services_t/pycurl_manager_t.py
Labels: Need wmagent branch, Python3

#10261 Make WMAgent job wrapper slightly more verbose; fix one error message
  etc/submit.sh
Labels: Need wmagent branch

#10265 Check if DID exists before creating a replication rule
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMCore/Services/Rucio/Rucio.py
Labels: Need wmagent branch

#10275 Skip RSE quota check for RelVal input data placement; added rule meta data
  src/python/WMCore/MicroService/DataStructs/Workflow.py
  src/python/WMCore/MicroService/Unified/MSTransferor.py
  src/python/WMCore/Services/Rucio/Rucio.py
  test/python/WMCore_t/MicroService_t/DataStructs_t/Workflow_t.py
Labels: Patch Production Services

#10262 [py2py3] Migration at level scr/python/A/B/C - slice 5
  src/python/WMCore/GroupUser/Interface.py
  src/python/WMCore/JobStateMachine/SummaryDB.py
  src/python/WMCore/Services/CRIC/CRIC.py
  src/python/WMCore/Services/FWJRDB/FWJRDBAPI.py
  src/python/WMCore/Services/ReqMgr/ReqMgr.py
  src/python/WMCore/Services/UserFileCache/UserFileCache.py
  src/python/WMCore/Storage/Registry.py
  src/python/WMCore/Storage/StageInMgr.py
  src/python/WMCore/Storage/StageOutImpl.py
  src/python/WMCore/Storage/StageOutImplV2.py
  src/python/WMCore/WMBS/File.py
  src/python/WMCore/WMBS/Mask.py
  src/python/WMCore/WMBS/Workflow.py
  src/python/WMCore/WMSpec/Persistency.py
  src/python/WMCore/WorkQueue/WorkQueueBase.py
  src/python/WMQuality/Emulators/CRICClient/MockCRICApi.py
  test/python/WMComponent_t/DBS3Buffer_t/DBSBufferFile_t.py
  test/python/WMCore_t/Database_t/CouchUtils_t.py
  test/python/WMCore_t/Database_t/DBCore_t.py
  test/python/WMCore_t/GroupUser_t/Interface_t.py
  test/python/WMCore_t/WMBS_t/Workflow_t.py
  test/python/WMCore_t/WMLogging_t.py
Labels: Python3, py2py3 slice

#10277 [py2py3] Migration at level scr/python/A/B/C - slice 6
  src/python/WMComponent/DBS3Buffer/DBSBufferUtil.py
  src/python/WMCore/ACDC/CouchFileset.py
  src/python/WMCore/ACDC/CouchService.py
  src/python/WMCore/Database/MySQLCore.py
  src/python/WMCore/JobSplitting/JobFactory.py
  src/python/WMCore/JobSplitting/MinFileBased.py
  src/python/WMCore/JobSplitting/ParentlessMergeBySize.py
  src/python/WMCore/JobSplitting/RunBased.py
  src/python/WMCore/JobSplitting/SiblingProcessingBased.py
  src/python/WMCore/JobSplitting/SizeBased.py
  src/python/WMCore/JobSplitting/SplitFileBased.py
  src/python/WMCore/JobSplitting/TwoFileBased.py
  src/python/WMCore/JobSplitting/WMBSMergeBySize.py
  src/python/WMCore/Storage/DeleteMgr.py
  src/python/WMCore/WMBS/Job.py
  src/python/WMCore/WMBS/Subscription.py
  test/python/WMComponent_t/DBS3Buffer_t/DBSBufferUtil_t.py
  test/python/WMCore_t/ACDC_t/CouchCollection_t.py
  test/python/WMCore_t/ACDC_t/CouchFileset_t.py
  test/python/WMCore_t/ACDC_t/CouchService_t.py
  test/python/WMCore_t/JobSplitting_t/FixedDelay_t.py
  test/python/WMCore_t/JobSplitting_t/RunBased_t.py
  test/python/WMCore_t/JobSplitting_t/SizeBased_t.py
  test/python/WMCore_t/WMBS_t/Job_t.py
Labels: Python3, py2py3 slice

#10284 [py2py3] Migration at level scr/python/A/B/C - slice 7
  src/python/WMCore/ACDC/DataCollectionService.py
  src/python/WMCore/BossAir/RunJob.py
  src/python/WMCore/Database/DBFactory.py
  src/python/WMCore/JobSplitting/EventAwareLumiByWork.py
  src/python/WMCore/JobSplitting/EventBased.py
  src/python/WMCore/WMInit.py
  src/python/WMCore/WebTools/NestedModel.py
  src/python/WMCore/WebTools/RESTApi.py
  src/python/WMCore/WebTools/RESTModel.py
  src/python/WMCore/WebTools/WebAPI.py
  src/python/WMQuality/TestInit.py
  test/python/WMCore_t/ACDC_t/DataCollectionService_t.py
  test/python/WMCore_t/BossAir_t/RunJob_t.py
  test/python/WMCore_t/JobSplitting_t/EventAwareLumiByWork_t.py
  test/python/WMCore_t/JobSplitting_t/EventBased_t.py
  test/python/WMCore_t/WMBS_t/JobGroup_t.py
Labels: Python3, py2py3 slice

#10289 [py2py3] Migration at level scr/python/A/B/C - slice 8
  src/python/WMCore/MicroService/Service/Data.py
  src/python/WMCore/ProcessPool/ProcessPool.py
  src/python/WMCore/Services/DBS/DBS3Reader.py
  src/python/WMCore/Services/DBS/DBSWriterObjects.py
  src/python/WMCore/Services/DBS/ProdException.py
  src/python/WMQuality/TestInitCouchApp.py
  test/python/WMCore_t/ProcessPool_t/ProcessPool_t.py
Labels: Python3, py2py3 slice

#10290 [py2py3] Migration at level scr/python/A/B/C - slice 9
  src/python/WMCore/WMBS/MySQL/Create.py
  src/python/WMCore/WMBS/MySQL/Files/AddRunLumi.py
  src/python/WMCore/WMBS/MySQL/Files/GetByID.py
  src/python/WMCore/WMBS/MySQL/Files/GetByLFN.py
  src/python/WMCore/WMBS/MySQL/Files/GetForJobSplittingByID.py
  src/python/WMCore/WMBS/MySQL/Files/GetLocationBulk.py
  src/python/WMCore/WMBS/MySQL/Files/GetRunLumiFile.py
  src/python/WMCore/WMBS/MySQL/Files/SetLocation.py
  src/python/WMCore/WMBS/MySQL/Files/SetLocationByLFN.py
  src/python/WMCore/WMBS/MySQL/JobGroup/GetLocationsForJobs.py
  src/python/WMCore/WMBS/MySQL/JobGroup/GetSite.py
  src/python/WMCore/WMBS/MySQL/Jobs/AddFiles.py
  src/python/WMCore/WMBS/MySQL/Jobs/ChangeState.py
  src/python/WMCore/WMBS/MySQL/Jobs/GetAllJobs.py
  src/python/WMCore/WMBS/MySQL/Jobs/GetCache.py
  src/python/WMCore/WMBS/MySQL/Jobs/GetState.py
  src/python/WMCore/WMBS/MySQL/Jobs/GetTask.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadFiles.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadForErrorHandler.py
  src/python/WMCore/WMBS/MySQL/Jobs/LoadForTaskArchiver.py
  src/python/WMCore/WMBS/MySQL/Jobs/Monitoring.py
  src/python/WMCore/WMBS/MySQL/Locations/AddPNNs.py
  src/python/WMCore/WMBS/MySQL/Locations/GetPendingSlots.py
  src/python/WMCore/WMBS/MySQL/Locations/GetRunningSlots.py
  src/python/WMCore/WMBS/MySQL/Locations/ListSites.py
  src/python/WMCore/WMBS/MySQL/Masks/Save.py
  src/python/WMCore/WMBS/MySQL/Monitoring/SubscriptionStatus.py
  src/python/WMCore/WMBS/MySQL/Monitoring/TaskSummaryByWorkflow.py
  src/python/WMCore/WMBS/MySQL/Monitoring/WorkflowSummary.py
  src/python/WMCore/WMBS/MySQL/Subscriptions/CountFinishedSubscriptionsByWorkflow.py
  src/python/WMCore/WMBS/MySQL/Subscriptions/GetAvailableFiles.py
  src/python/WMCore/WMBS/MySQL/Subscriptions/GetAvailableFilesMeta.py
  src/python/WMCore/WMBS/MySQL/Subscriptions/GetFilesForMerge.py
  src/python/WMCore/WMBS/MySQL/Workflow/RemoveDuplicates.py
Labels: Python3, py2py3 slice

#10295 [py2py3] Migration at level scr/python/A/B/C - slice 10
  src/python/WMComponent/RucioInjector/Database/MySQL/GetMigratedBlocks.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetUninjectedFiles.py
  src/python/WMCore/Agent/Database/CreateAgentBase.py
  src/python/WMCore/Agent/Database/MySQL/Create.py
  src/python/WMCore/ReqMgr/DataStructs/ReqMgrConfigDataCache.py
  src/python/WMCore/ReqMgr/DataStructs/Request.py
  src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py
  src/python/WMCore/Services/LogDB/LogDB.py
  src/python/WMCore/Services/LogDB/LogDBBackend.py
  src/python/WMCore/Services/LogDB/LogDBReport.py
  src/python/WMCore/Services/RequestDB/RequestDBReader.py
  src/python/WMCore/WorkQueue/DataStructs/ACDCBlock.py
  src/python/WMCore/WorkQueue/DataStructs/CouchWorkQueueElement.py
  src/python/WMCore/WorkQueue/DataStructs/WorkQueueElement.py
  src/python/WMCore/WorkQueue/DataStructs/WorkQueueElementResult.py
  src/python/WMCore/WorkQueue/DataStructs/WorkQueueElementsSummary.py
  test/python/WMCore_t/WorkQueue_t/DataStructs_t/WorkQueueElement_t.py
Labels: Python3, py2py3 slice
