Repository dmwm/WMCore, pull requests merged in 2021-04, with the labels that each got.

#10439 [py2py3] fix issue #10398
  test/python/WMCore_t/Database_t/DBCore_t.py
Labels: Python3

#10443 Changes in Slice 17 are causing #10381
  src/python/WMCore/Configuration.py
Labels: Need wmagent branch, Python3

#10444 Force cmsweb-prod in DBS3Reader
  src/python/WMCore/Services/DBS/DBS3Reader.py
Labels: Need wmagent branch

#10441 [py2py3] fix all pylint --py3k issues and warnings
  src/python/WMCore/Agent/Database/DestroyAgentBase.py
  src/python/WMCore/JobSplitting/EventAwareLumiByWork.py
  src/python/WMCore/REST/Server.py
  src/python/WMCore/ResourceControl/ResourceControl.py
  src/python/WMCore/Services/LogDB/LogDBBackend.py
  src/python/WMCore/WebTools/Masthead.py
  test/python/Utils_t/IteratorTools_t.py
  test/python/Utils_t/Utilities_t.py
  test/python/WMCore_t/BossAir_t/SimpleCondorPlugin_t.py
  test/python/WMCore_t/Cache_t/WMConfigCache_t.py
  test/python/WMCore_t/Database_t/RotatingDatabase_t.py
  test/python/WMCore_t/FwkJobReport_t/ReportIntegration_t.py
  test/python/WMCore_t/Services_t/CRIC_t/CRIC_t.py
  test/python/WMCore_t/WMBS_t/CursorLeak_t.py
  test/python/WMCore_t/WMBS_t/JobSplitting_t/EventBased_t.py
  test/python/WMCore_t/WMBS_t/JobSplitting_t/LumiBased_t.py
  test/python/WMCore_t/WebTools_t/DummyRESTModel.py
Labels: Python3

#10454 Create symbolic links in deploy-wmagent
  deploy/deploy-wmagent.sh
Labels: Do not merge yet, Work in progress

#10465 [py2py3] Apply changes from pylint --py3k to files involved in #10012
  src/python/WMCore/DataStructs/File.py
  src/python/WMCore/DataStructs/Run.py
  test/python/WMCore_t/DataStructs_t/File_t.py
  test/python/WMCore_t/DataStructs_t/Run_t.py
Labels: Python3

#10470 Only create Rucio connection in PileupFetcher if there is a pileup dataset
  src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py
Labels: Need wmagent branch
