Repository dmwm/WMCore, pull requests merged in 2022-04, with the labels that each got.

#11067 Assign the correct activity for Tape_Test RSEs
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
Labels: PR: Need wmagent branch

#11083 When ScramArch is empty str/list/None, return any as required_os
  src/python/WMCore/BossAir/Plugins/BasePlugin.py
  test/python/WMCore_t/BossAir_t/BasePlugin_t.py
Labels: PR: Need wmagent branch

#11077 If job requires rhel8 container, use slc7 python libraries
  etc/submit_py3.sh
Labels: PR: Need wmagent branch

#11088 Enhance logic to map ScramArch to OS
  src/python/WMCore/BossAir/Plugins/BasePlugin.py
  test/python/WMCore_t/BossAir_t/BasePlugin_t.py
Labels: PR: Need wmagent branch

#11097 Support adding diskless resources into the database
  bin/wmagent-resource-control
  deploy/deploy-wmagent.sh
Labels: PR: Need wmagent branch

#11101 move ckey/cert functions to Utils.CertTools
  src/python/Utils/CertTools.py
  src/python/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py
  src/python/WMCore/MicroService/Tools/Common.py
  src/python/WMCore/MicroService/Tools/PycurlRucio.py
Labels: PR: Work in progress, Enhancement

#10998 Remove PFNs from a final document we send to WMArchive
  src/python/WMCore/Services/WMArchive/DataMap.py
Labels: PR: Do not merge yet, PR: Work in progress

#11111 Fix redundant WHERE NOT EXISTS clause parameters for protecting from Unique constraints in ORACLE for DBS3Buffer/NewSubscriptions
  src/python/WMComponent/DBS3Buffer/Oracle/NewSubscription.py
Labels: PR: Patch Production Agent

#11113 Ensure aborted/force-complete workflows leave no elements behind
  bin/kill-workflow-in-global
  src/python/WMCore/ReqMgr/CherryPyThreads/StatusChangeTasks.py
  src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py
  src/python/WMCore/Services/WorkQueue/WorkQueue.py
  test/python/WMCore_t/Services_t/WorkQueue_t/WorkQueue_t.py
Labels: PR: Further tests needed
