Repository dmwm/WMCore, pull requests merged in 2022-06, with the labels that each got.

#11001 [CouchDB] Bundle of fixes required for migration to CouchDB 3.x
  src/couchapps/WorkQueue/filters/queueFilter.js
  src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py
  src/python/WMCore/Database/CMSCouch.py
  src/python/WMCore/Services/RequestDB/RequestDBReader.py
  src/python/WMCore/Services/Requests.py
  src/python/WMCore/WorkQueue/WorkQueueBackend.py
  test/python/WMCore_t/DataStructs_t/MathStructs_t/ContinuousSummaryHistogram_t.py
  test/python/WMCore_t/DataStructs_t/MathStructs_t/DiscreteSummaryHistogram_t.py
  test/python/WMCore_t/Database_t/CMSCouch_t.py
  test/python/WMCore_t/Database_t/RotatingDatabase_t.py
  test/python/WMCore_t/JobStateMachine_t/Couchapp_t.py
  test/python/WMCore_t/Services_t/Requests_t.py
  test/python/WMCore_t/WorkQueue_t/WorkQueue_t.py
Labels: PR: Need wmagent branch, PR: Two approvals required

#11179 Ensure dataset_lifetime bind is defined for DBS3Buffer/NewSubscription
  src/python/WMComponent/DBS3Buffer/MySQL/NewSubscription.py
Labels: PR: Need wmagent branch

#11176 Provide uniform way to handle DBS server errors
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
  src/python/WMQuality/Emulators/DBSClient/DBS3API.py
  test/python/WMComponent_t/DBS3Buffer_t/DBSUpload_t.py
Labels: PR: Need wmagent branch

#11177 Update deployment scripts for 2.0.4 and test campaigns in central couch
  bin/adhoc-scripts/parseUnifiedCampaigns.py
  deploy/WMAgent.production
  deploy/WMAgent.testbed
  deploy/deploy-wmagent.sh
Labels: PR: Do not merge yet, PR: Work in progress
