Repository dmwm/WMCore, pull requests merged in 2022-02, with the labels that each got.

#10972 JobAccountant workaround for StepChain jobs with duplicate files - wmagent 1.5.7 branch
  src/python/WMComponent/JobAccountant/AccountantWorker.py
Labels: Patch Production Agent

#10963 Aggregate DBS results from Go server
  src/python/WMCore/MicroService/Tools/Common.py
  test/python/WMCore_t/MicroService_t/Tools_t/Common_t.py
Labels: Do not merge yet

#10687 Account for failed deletions on a per directory basis
  src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
  src/python/WMCore/MicroService/MSUnmerged/MSUnmergedRSE.py
  test/python/WMCore_t/MicroService_t/MSUnmerged_t/MSUnmergedRSE_t.py
Labels: Do not merge yet

#10984 Bump dbs3-client to 4.0.6
  requirements_py3.txt
Labels: Need wmagent branch, Need cmsweb branch

#10976 Update requirements.txt and PyPI build scripts for py3 stack
  requirements.txt
  setup_dependencies.py
  tools/build_pypi_packages.sh
Labels: Update documentation

#10950 Add lifetime to RucioContainers shipping to disk sites
  src/python/WMComponent/DBS3Buffer/MySQL/Create.py
  src/python/WMComponent/DBS3Buffer/MySQL/NewSubscription.py
  src/python/WMComponent/DBS3Buffer/Oracle/Create.py
  src/python/WMComponent/DBS3Buffer/Oracle/NewSubscription.py
  src/python/WMComponent/RucioInjector/Database/MySQL/GetUnsubscribedDatasets.py
  src/python/WMComponent/RucioInjector/RucioInjectorPoller.py
  src/python/WMCore/WMSpec/StdSpecs/StdBase.py
  src/python/WMCore/WMSpec/WMTask.py
  src/python/WMCore/WMSpec/WMWorkload.py
  test/python/WMCore_t/WMSpec_t/StdSpecs_t/StepChain_t.py
  test/python/WMCore_t/WMSpec_t/WMTask_t.py
Labels: Do not merge yet

#11007 Add mockMongoDB to MSUnmerged and MongoDB Class init optoins
  src/python/WMCore/Database/MongoDB.py
  src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
  test/python/WMCore_t/MicroService_t/MSUnmerged_t/MSUnmerged_t.py
Labels: squashing needed
