Repository dmwm/WMCore, pull requests merged in 2022-03, with the labels that each got.

#11023 Allow MongoDB to be instantiated without mongomock library
  src/python/WMCore/Database/MongoDB.py
Labels: One approval required

#11021 Enhancements to the GH issues and PRs workflows
  CONTRIBUTING.rst
  standards/README
Labels: Two approvals required

#11029 Reorder RSE's status and record age checks from RucioConMon.
  src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
Labels: Patch Production Services, One approval required

#11031 Fix MSTransferor typo calling getName method
  src/python/WMCore/MicroService/MSTransferor/MSTransferor.py
Labels: Patch Production Services

#11032 MSTransferor: fix positional and kwargs passed to sendAlert API
  src/python/WMCore/MicroService/MSTransferor/MSTransferor.py
Labels: One approval required

#11045 [CouchDB] Do not sanitize couch url in JobAccountant
  src/python/WMComponent/JobAccountant/AccountantWorker.py
  src/python/WMComponent/TaskArchiver/CleanCouchPoller.py
  src/python/WMCore/Database/CMSCouch.py
  src/python/WMCore/WorkQueue/WorkQueueBackend.py
Labels: One approval required

#11043 Adjust processing version to be integer
  src/python/WMComponent/DBS3Buffer/DBSBufferBlock.py
  src/python/WMComponent/DBS3Buffer/DBSBufferFile.py
  src/python/WMComponent/DBS3Buffer/MySQL/Create.py
  src/python/WMComponent/DBS3Buffer/MySQL/FindDASToUpload.py
  src/python/WMComponent/DBS3Buffer/MySQL/UpdateDataset.py
  src/python/WMComponent/DBS3Buffer/Oracle/Create.py
  src/python/WMCore/WMSpec/WMWorkload.py
  test/python/WMComponent_t/DBS3Buffer_t/DBSBufferFile_t.py
  test/python/WMComponent_t/JobAccountant_t/JobAccountant_t.py
Labels: High Priority, DB schema change, DBS

#11050 Add getProtectedLFNsT0 to WMStatsServer && Call it from MSUnmerged.
  src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
  test/python/WMCore_t/MicroService_t/MSUnmerged_t/MSUnmerged_t.py
Labels: One approval required
