Repository dmwm/WMCore, pull requests merged in 2022-12, with the labels that each got.

#11381 Replace dash in exporter name
  src/python/Utils/CPMetrics.py
  test/python/Utils_t/CPMetrics_t.py
Labels: Monitoring, Kubernetes

#11377 Add new GH Action workflows to build WMCore images
  .github/workflows/docker_images_template.yaml
  .github/workflows/pypi_build_and_images.yaml
  .github/workflows/pypi_build_publish_template.yaml
  .github/workflows/pypy_build_publish.yaml
Labels: deployment, containerization, Kubernetes

#11379 Change metadata field in the Grafana SSB query
  src/python/WMCore/Services/MonIT/Grafana.py
Labels: PR: Need wmagent branch
