Repository dmwm/WMCore, pull requests merged in 2023-04, with the labels that each got.

#11526 Final tweaks to MSPileup
  src/python/WMCore/MicroService/MSPileup/MSPileupTasks.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupTasks_t.py
Labels: PR: Do not merge yet, PR: Work in progress

#11529 Fix clean-up query
  src/python/WMCore/MicroService/MSPileup/MSPileupData.py
  src/python/WMCore/MicroService/MSPileup/MSPileupTasks.py
Labels: BUG, MSPileup

#11540 Fixing racing conditions in unit tests using CouchDB
  src/python/WMQuality/TestInitCouchApp.py
Labels: PR: Work in progress, QPrio: High

#11573 Remove postToAMQ (post_to_amq) and fix typo in doc_type_amq
  src/python/WMCore/MicroService/MSPileup/MSPileupMonitoring.py
Labels: PR: Need cmsweb branch

#11572 Fix manage path in the restartComponent script
  deploy/deploy-wmagent.sh
  deploy/restartComponent.sh
Labels: PR: Need wmagent branch

#11502 Add new CMSCouch exception for Request Entity Too Large
  etc/WMAgentConfig.py
  src/python/WMCore/Database/CMSCouch.py
  src/python/WMCore/JobStateMachine/ChangeState.py
Labels: PR: Need wmagent branch

#11579 MSPileup: detect active containers with no wmcore_trasnferor rules
  src/python/WMCore/MicroService/MSPileup/MSPileupTasks.py
Labels: PR: Need cmsweb branch
