Repository dmwm/WMCore, pull requests merged in 2023-01, with the labels that each got.

#11375 Switch to use DBSError reason/srvCode instead of if/else exception block
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
Labels: Enhancement, DBS

#11437 Fix broken syntax for the f-string in DBSUploadPoller
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
Labels: PR: Need wmagent branch

#11442 Do not duplicate error messages in DBS3Upload
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
Labels: PR: Need wmagent branch

#11433 Ensure JobAccountant does not insert files without any location
  src/python/WMComponent/JobAccountant/AccountantWorker.py
  test/python/WMComponent_t/JobAccountant_t/JobAccountant_t.py
  test/python/WMComponent_t/JobAccountant_t/fwjrs/NoLocation.pkl
Labels: PR: Need wmagent branch

#11438 Data management layer for MSPileup data-service
  src/python/Utils/Timers.py
  src/python/WMCore/MicroService/MSPileup/DataStructs/MSPileupObj.py
  src/python/WMCore/MicroService/MSPileup/DataStructs/__init__.py
  src/python/WMCore/MicroService/MSPileup/MSPileup.py
  src/python/WMCore/MicroService/MSPileup/MSPileupData.py
  src/python/WMCore/MicroService/MSPileup/MSPileupError.py
  test/python/Utils_t/Timers_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupData_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupObj_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/__init__.py
Labels: PR: Do not merge yet, PR: Work in progress

#11457 Corrected GQ -> LQ data acquisition in slices
  etc/WMAgentConfig.py
  src/python/WMCore/WorkQueue/WorkQueue.py
  src/python/WMCore/WorkQueue/WorkQueueBackend.py
Labels: PR: Need wmagent branch
