Repository dmwm/WMCore, pull requests merged in 2023-02, with the labels that each got.

#11443 MSPileup service HTTP APIs
  src/python/WMCore/MicroService/DataStructs/DefaultStructs.py
  src/python/WMCore/MicroService/MSCore/MSManager.py
  src/python/WMCore/MicroService/MSPileup/MSPileup.py
  src/python/WMCore/MicroService/MSPileup/MSPileupData.py
  src/python/WMCore/MicroService/Service/Data.py
  src/python/WMCore/MicroService/Service/RestApiHub.py
  test/python/WMCore_t/MicroService_t/MSManager_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileup_t.py
Labels: PR: Do not merge yet, PR: Work in progress

#11475 Fix MSPileup APIs
  src/python/WMCore/MicroService/MSPileup/DataStructs/MSPileupObj.py
  src/python/WMCore/MicroService/MSPileup/MSPileup.py
  src/python/WMCore/MicroService/MSPileup/MSPileupData.py
  src/python/WMCore/MicroService/MSPileup/MSPileupError.py
  src/python/WMCore/MicroService/Service/Data.py
  src/python/WMCore/REST/Format.py
  src/python/WMCore/REST/Server.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupData_t.py
Labels: BUG, PR: Work in progress, PR: Update documentation

#11462 Skip auth check in case of localhost usage
  src/python/WMCore/REST/Auth.py
  test/python/WMCore_t/REST_t/Simple_t.py
Labels: HTTP, Auth, web development

#11473 Deprecate TFC override for multi-step jobs
  src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py
  src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
  test/python/WMCore_t/WMRuntime_t/Scripts_t/SetupCMSSWPset_t.py
Labels: PR: Need wmagent branch

#11481 Adopt CMS_PATH and SITECONFIG_PATH to locate the site catalog
  src/python/WMCore/Storage/SiteLocalConfig.py
  src/python/WMCore/WMRuntime/Tools/Scram.py
  test/python/WMCore_t/Misc_t/Runtime_t.py
  test/python/WMCore_t/Storage_t/SiteLocalConfig_t.py
  test/python/WMCore_t/Storage_t/StageOutMgr_t.py
  test/python/WMCore_t/WMSpec_t/Steps_t/Executors_t/LogArch_t.py
  test/python/WMCore_t/WMSpec_t/Steps_t/Executors_t/StageOut_t.py
Labels: PR: Need wmagent branch

#11487 First implementation of MSPileup data placement logic via MSPileupTasks class
  src/python/WMCore/MicroService/MSPileup/DataStructs/MSPileupObj.py
  src/python/WMCore/MicroService/MSPileup/MSPileupReport.py
  src/python/WMCore/MicroService/MSPileup/MSPileupTaskManager.py
  src/python/WMCore/MicroService/MSPileup/MSPileupTasks.py
  src/python/WMCore/Services/Rucio/Rucio.py
  test/data/Mock/RucioMockData.json
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupData_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupObj_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupReport_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupTasks_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileup_t.py
Labels: PR: Work in progress
