Repository dmwm/WMCore, pull requests merged in 2023-11, with the labels that each got.

#11786 Fix ChangeState logic for limiting number of docs to commit in bulk
  src/python/WMCore/JobStateMachine/ChangeState.py
Labels: PR: Need wmagent branch

#11765 Add support for customName (custom container DID)
  src/python/WMCore/MicroService/MSPileup/DataStructs/MSPileupObj.py
  src/python/WMCore/MicroService/MSPileup/MSPileupData.py
  src/python/WMCore/MicroService/MSPileup/MSPileupTaskManager.py
  src/python/WMCore/MicroService/MSPileup/MSPileupTasks.py
  src/python/WMQuality/Emulators/RucioClient/MockRucioApi.py
  test/data/Mock/RucioMockData.json
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupData_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupObj_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupTasks_t.py
Labels: PR: Do not merge yet, PR: Work in progress

#11769 Add customName to JSON data and adhoc script
  bin/adhoc-scripts/adjustMongoDocs.py
  test/data/WMCore/MicroService/DataStructs/pileups.json
  test/data/WMCore/MicroService/DataStructs/pileups_dev.json
Labels: MSPileup

#11768 Make DBS3Upload slightly more verbose
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
Labels: PR: Do not merge yet, PR: Work in progress

#11802 Add transition attribute to MSPIleup document
  src/python/WMCore/MicroService/MSPileup/DataStructs/MSPileupObj.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupData_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupMonitoring_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupObj_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileupTasks_t.py
  test/python/WMCore_t/MicroService_t/MSPileup_t/MSPileup_t.py
Labels: MSPileup
