Repository dmwm/WMCore, pull requests merged in 2025-01, with the labels that each got.

#12219 Switch updateSiteList to updateElementsByWorkflow API
  src/python/WMComponent/WorkflowUpdater/SiteListPoller.py
  src/python/WMCore/Services/WorkQueue/WorkQueue.py
Labels: Enhancement

#12221 Register transfer REST APIs
  src/python/WMCore/MicroService/Service/RestApiHub.py
Labels: MSTransferor, web development

#12207 Improve patchComponent && Add patchCluster scripts
  bin/patchCluster.sh
  bin/patchComponent.sh
Labels: Documentation

#12220 Add HTTP request from ReqMgr2 to MSTransferor to trigger site list update
  src/python/WMComponent/WorkflowUpdater/WorkflowUpdaterPoller.py
  src/python/WMCore/MicroService/MSCore/MSManager.py
  src/python/WMCore/MicroService/MSTransferor/MSTransferor.py
  src/python/WMCore/ReqMgr/Service/Request.py
  src/python/WMCore/Services/MSPileup/MSPileupUtils.py
  src/python/WMCore/Services/MSUtils/MSUtils.py
  src/python/WMCore/Services/MSUtils/__init__.py
  src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py
  src/python/WMCore/WorkQueue/DataLocationMapper.py
  src/python/WMCore/WorkQueue/Policy/Start/StartPolicyInterface.py
  test/python/WMCore_t/ReqMgr_t/TestConfig.py
  test/python/WMCore_t/Services_t/MSPileup_t/MSPileupUtils_t.py
Labels: Enhancement
