Repository dmwm/WMCore, pull requests merged in 2025-05, with the labels that each got.

#12312 Properly parse and handle DBS client errors
  src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
  src/python/WMCore/Services/DBS/DBSErrors.py
  src/python/WMCore/Services/DBS/DBSUtils.py
  src/python/WMQuality/Emulators/DBS/DBSUtils.py
  src/python/WMQuality/Emulators/DBS/__init__.py
  test/python/WMCore_t/Services_t/DBS_t/DBSUtils_t.py
Labels: PR: squashing needed

#12302 Improve monitoring information of WMAgent components
  bin/wmcoreD
  src/python/Utils/ProcFS.py
  src/python/Utils/ProcessStats.py
  src/python/Utils/Utilities.py
  src/python/WMComponent/AnalyticsDataCollector/DataCollectAPI.py
  src/python/WMCore/Agent/Daemon/Details.py
  test/python/Utils_t/ProcFS_t.py
  test/python/Utils_t/ProcessStats_t.py
  test/python/Utils_t/Utilities_t.py
Labels: New Feature, WMAgent, WMStats, Monitoring

#12346 Split patch files by source files edited && Apply them separately
  bin/patchComponent.sh
Labels: PR: squashing needed

#12359 switch from distribution.data_files to distribution.package_data
  setup_build.py
Labels: Python3, PR: squashing needed, Technical Debt

#12372 Change look-up states for process status
  src/python/WMComponent/AnalyticsDataCollector/DataCollectAPI.py
Labels: New Feature, WMAgent, WMStats, Monitoring
